package com.cognizant.ormlearn.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.cognizant.ormlearn.model.Country;
import com.cognizant.ormlearn.repository.CountryRepository;

/**
 * CountryService - Service Layer Class
 *
 * Purpose:
 *   Acts as the business logic layer between the controller/main class
 *   and the repository (data access) layer.
 *
 *   In this hands-on, it wraps the repository calls and provides
 *   transaction management.
 *
 * @Service:
 *   - Marks this class as a Spring-managed Service bean.
 *   - Enables component scanning to detect and register this bean
 *     in the Spring Application Context.
 *   - Semantically different from @Component — signals that this
 *     class holds business logic.
 */
@Service
public class CountryService {

    /**
     * @Autowired:
     *   - Tells Spring to inject the CountryRepository bean automatically.
     *   - Spring finds the proxy implementation of CountryRepository
     *     (auto-generated by Spring Data JPA) and injects it here.
     *   - This is called Dependency Injection (DI).
     */
    @Autowired
    private CountryRepository countryRepository;

    /**
     * getAllCountries() - Retrieves all country records from the database.
     *
     * @Transactional:
     *   - Ensures this method runs within a database transaction.
     *   - If anything goes wrong, the transaction is automatically rolled back.
     *   - If everything succeeds, the transaction is committed.
     *   - Without this, lazy-loaded associations could throw
     *     LazyInitializationException outside of a Hibernate session.
     *
     * How it works:
     *   1. Spring opens a Hibernate session and begins a transaction.
     *   2. countryRepository.findAll() executes:
     *         SELECT co_code, co_name FROM country;
     *   3. Hibernate maps each row to a Country object.
     *   4. The list of Country objects is returned.
     *   5. Spring commits the transaction and closes the session.
     *
     * @return List<Country> - All rows from the 'country' table as Country objects.
     */
    @Transactional
    public List<Country> getAllCountries() {
        return countryRepository.findAll();
    }
}
