package com.cognizant.taskmanager.model;

/**
 * ============================================================
 * Task — The domain model (POJO)
 * ============================================================
 *
 * Represents a single task with three fields:
 *   - id        : unique identifier (auto-generated by the controller)
 *   - title     : short description of the task
 *   - completed : whether the task is done or not
 *
 * No JPA / Hibernate annotations are used because tasks are
 * stored in-memory (a ConcurrentHashMap in the controller).
 * Jackson will serialize/deserialize this class to/from JSON
 * automatically via Spring MVC's message converters.
 */
public class Task {

    // ── Fields ──────────────────────────────────────────────

    /** Unique identifier for the task (auto-assigned on creation) */
    private long id;

    /** Short description / name of the task */
    private String title;

    /** Whether the task has been completed */
    private boolean completed;

    // ── Constructors ────────────────────────────────────────

    /**
     * Default no-arg constructor.
     * Required by Jackson for JSON deserialization
     * (e.g. when @RequestBody maps incoming JSON → Task).
     */
    public Task() {
    }

    /**
     * Parameterized constructor for convenience.
     *
     * @param id        unique task id
     * @param title     task description
     * @param completed task completion status
     */
    public Task(long id, String title, boolean completed) {
        this.id = id;
        this.title = title;
        this.completed = completed;
    }

    // ── Getters & Setters ───────────────────────────────────

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public boolean isCompleted() {
        return completed;
    }

    public void setCompleted(boolean completed) {
        this.completed = completed;
    }

    // ── toString ────────────────────────────────────────────

    @Override
    public String toString() {
        return "Task{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", completed=" + completed +
                '}';
    }
}
